# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59be5dc4af655004f061e27a3adcdac15cc90e396cb8921d9ed3194dc04ecfc2502d32e96278119d461fee05fe0e3509c3c103279f35ecc7417ec3014ebb4dd0

test:
  secret_key_base: ab8410b16bed057086d581008cc6622103d7f06f308c5a8e7e5e6857d4cc8894e22dcd24bbdc000267c6129f3be7663d1fbcc1c73fdad89cb920469e3834abad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
